In [26]:
from pathlib import Path
import pandas as pd

In [27]:
#Create raw folder path
root_fldr = Path.cwd().parent
raw_fldr = root_fldr / "data" / "raw"
processed_fldr = root_fldr / "data" / "processed"

#Create raw csv file variables
fire25_csv = raw_fldr / "fire_25_TD.csv"
rxburn25_csv = raw_fldr / "rxburn_25_TD.csv"

#Import csv as data frames
fire25_raw = pd.read_csv(fire25_csv)
rxburn_raw = pd.read_csv(rxburn25_csv)

In [28]:
#Report csv dimensions
print(fire25_raw.shape)
print(rxburn_raw.shape)

(23334, 26)
(11975, 23)

In [29]:
#Report head of fire25
fire25_raw.head()

,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,IRWINID,ALARM_DATE,CONT_DATE,C_METHOD,...,FIRE_NUM,Shape_Length,Shape_Area,GlobalID,d_STATE,d_AGENCY,d_UNIT_ID,d_C_METHOD,d_CAUSE,d_OBJECTIVE
0,2025.0,CA,USF,LPF,GIFFORD,00002181,{08A6358F-8301-4093-9988-E265C8F6F0A9},8/1/2025 0:00:00,10/14/2025 0:00:00,3,...,NaN,257388.320379,5.326211e+08,{E87207FF-BD3D-4836-8A89-AD218A20B17E},California,USDA Forest Service,Los Padres National Forest,Infrared,Unknown / Unidentified,Suppression (Wildfire)
1,2025.0,CA,USF,LPF,MADRE,00001817,{1AB682F7-CC0F-4DCE-87A4-FA4A9B67AB05},7/2/2025 0:00:00,7/26/2025 0:00:00,7,...,NaN,191846.167384,3.269014e+08,{C59C71E2-F79F-440B-8C84-48058988F3CF},California,USDA Forest Service,Los Padres National Forest,Mixed Collection Methods,Unknown / Unidentified,Suppression (Wildfire)
2,2025.0,CA,USF,SNF,GARNET,00001684,{68B988A1-C190-4F0C-9BEA-A658D389D167},8/24/2025 0:00:00,10/23/2025 0:00:00,3,...,NaN,234717.355087,2.428892e+08,{DDD0B278-7655-4F20-829D-FEEEF1DC935F},California,USDA Forest Service,Sierra National Forest,Infrared,Lightning,Suppression (Wildfire)
3,2025.0,CA,CDF,FKU,SALT,00018739,{7F4A1474-6439-44F3-8F0D-083DCFD33639},9/2/2025 0:00:00,9/17/2025 0:00:00,7,...,NaN,90080.360959,1.034115e+08,{6817A72C-90CF-4CD4-8F26-2B9622F1F140},California,California Department of Forestry and Fire Pro...,Fresno-Kings CAL FIRE,Mixed Collection Methods,Lightning,Suppression (Wildfire)
4,2025.0,CA,CDF,LDF,PALISADES,00000738,{A7EA5D21-F882-44B8-BF64-44AB11059DC1},1/7/2025 0:00:00,1/31/2025 0:00:00,7,...,NaN,116028.197349,9.489426e+07,{73730F90-5D60-4850-98C2-2431C4284CD7},California,California Department of Forestry and Fire Pro...,Los Angeles City FD,Mixed Collection Methods,Unknown / Unidentified,Suppression (Wildfire)

In [30]:
#fire info
fire25_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 23334 entries, 0 to 23333
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   YEAR_         23257 non-null  float64
 1   STATE         23334 non-null  str
 2   AGENCY        23286 non-null  str
 3   UNIT_ID       23274 non-null  str
 4   FIRE_NAME     16679 non-null  str
 5   INC_NUM       22379 non-null  str
 6   IRWINID       3633 non-null   str
 7   ALARM_DATE    17950 non-null  str
 8   CONT_DATE     10716 non-null  str
 9   C_METHOD      23334 non-null  int64
 10  CAUSE         23334 non-null  int64
 11  OBJECTIVE     23063 non-null  float64
 12  GIS_ACRES     23334 non-null  float64
 13  COMPLEX_ID    584 non-null    str
 14  COMPLEX_NAME  618 non-null    str
 15  COMMENTS      2962 non-null   str
 16  FIRE_NUM      17198 non-null  str
 17  Shape_Length  23334 non-null  float64
 18  Shape_Area    23334 non-null  float64
 19  GlobalID      23334 non-null  str
 20  d_STATE       23334 non-null  str
 21  d_AGENCY      23286 non-null  str
 22  d_UNIT_ID     23272 non-null  str
 23  d_C_METHOD    23334 non-null  str
 24  d_CAUSE       23334 non-null  str
 25  d_OBJECTIVE   23063 non-null  str
dtypes: float64(5), int64(2), str(19)
memory usage: 4.6 MB

In [31]:
#Report head of rxburn
rxburn_raw.head()

,YEAR_,STATE,AGENCY,UNIT_ID,TREATMENT_ID,TREATMENT_NAME,TREATMENT_TYPE,START_DATE,END_DATE,TREATED_AC,...,POST_CON_CLASS,Shape_Length,Shape_Area,d_STATE,d_AGENCY,d_UNIT_ID,d_TREATMENT_TYPE,d_RX_CONSUM,d_PRE_CON_CLASS,d_POST_CON_CLASS
0,2025.0,CA,BLM,CND,38441,BIL312D Stornetta Rx_FY25,3.0,10/1/2024 0:00:00,2/1/2025 0:00:00,15.0,...,NaN,1104.323979,59171.913798,California,Bureau of Land Management,Central CA District - BLM,Hand Pile Burn,3 - High Consumption,NaN,NaN
1,2025.0,CA,BLM,NOD,45361,BIL312D_FY25_Butte Pile RX,3.0,10/1/2024 0:00:00,2/1/2025 0:00:00,50.0,...,NaN,1799.301659,202342.766575,California,Bureau of Land Management,Northern CA District - BLM,Hand Pile Burn,4 - Very High Consumption,NaN,NaN
2,2025.0,CA,BLM,NOD,38421,BIL312D_FY25_North Horse Pile RX,3.0,2/10/2025 0:00:00,2/12/2025 0:00:00,229.0,...,NaN,5386.383188,925124.048407,California,Bureau of Land Management,Northern CA District - BLM,Hand Pile Burn,4 - Very High Consumption,NaN,NaN
3,2025.0,CA,BLM,NOD,40041,BIL312D_AGFO_WUI_Machine_Pile_Burn,3.0,10/1/2024 0:00:00,2/13/2025 0:00:00,116.0,...,NaN,3960.591710,469939.500485,California,Bureau of Land Management,Northern CA District - BLM,Hand Pile Burn,4 - Very High Consumption,NaN,NaN
4,2025.0,CA,BLM,CND,41684,Black Forest Rx_FY25,3.0,10/1/2024 0:00:00,3/25/2025 0:00:00,25.0,...,NaN,3452.593270,101650.358387,California,Bureau of Land Management,Central CA District - BLM,Hand Pile Burn,4 - Very High Consumption,NaN,NaN

In [32]:
#rxburn info
rxburn_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 11975 entries, 0 to 11974
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   YEAR_             11954 non-null  float64
 1   STATE             11975 non-null  str
 2   AGENCY            11975 non-null  str
 3   UNIT_ID           11957 non-null  str
 4   TREATMENT_ID      11503 non-null  str
 5   TREATMENT_NAME    10393 non-null  str
 6   TREATMENT_TYPE    9860 non-null   float64
 7   START_DATE        10202 non-null  str
 8   END_DATE          10002 non-null  str
 9   TREATED_AC        11190 non-null  float64
 10  GIS_ACRES         11973 non-null  float64
 11  RX_CONSUM         1081 non-null   float64
 12  PRE_CON_CLASS     504 non-null    float64
 13  POST_CON_CLASS    504 non-null    float64
 14  Shape_Length      11975 non-null  float64
 15  Shape_Area        11975 non-null  float64
 16  d_STATE           11975 non-null  str
 17  d_AGENCY          11973 non-null  str
 18  d_UNIT_ID         11927 non-null  str
 19  d_TREATMENT_TYPE  9860 non-null   str
 20  d_RX_CONSUM       1076 non-null   str
 21  d_PRE_CON_CLASS   503 non-null    str
 22  d_POST_CON_CLASS  503 non-null    str
dtypes: float64(9), str(14)
memory usage: 2.1 MB

In [33]:
#Clean imported data, filtering columns and rename
fire25 = fire25_raw.loc[:,['YEAR_', 'd_AGENCY', 'd_UNIT_ID', 'FIRE_NAME', 'INC_NUM', 'ALARM_DATE', 'CONT_DATE', 'GIS_ACRES', 'd_CAUSE', 'd_C_METHOD', 'd_OBJECTIVE', 'COMMENTS']]
rxburn25 = rxburn_raw.loc[:,['YEAR_', 'd_AGENCY', 'd_UNIT_ID', 'TREATMENT_ID', 'd_TREATMENT_TYPE', 'START_DATE', 'END_DATE', 'GIS_ACRES', 'd_PRE_CON_CLASS', 'd_POST_CON_CLASS', 'd_RX_CONSUM']]

#Convert Year to Integer data type
fire25['YEAR_'] = fire25['YEAR_'].astype('Int64') #pd.to_datetime(fire25['YEAR_'],format='%Y')
rxburn25['YEAR_'] = rxburn25['YEAR_'].astype('Int64')#pd.to_datetime(rxburn25['YEAR_'],format='%Y')

In [34]:
#Parse dates
fire25['ALARM_DATE'] = pd.to_datetime(fire25['ALARM_DATE'],format='%m/%d/%Y %H:%M:%S')
fire25['CONT_DATE'] = pd.to_datetime(fire25['CONT_DATE'],format='%m/%d/%Y %H:%M:%S')

rxburn25['START_DATE'] = pd.to_datetime(rxburn25['START_DATE'],format='%m/%d/%Y %H:%M:%S')
rxburn25['END_DATE'] = pd.to_datetime(rxburn25['END_DATE'],format='%m/%d/%Y %H:%M:%S')

In [35]:
#Rename columns
fire25 = fire25.rename(
    columns={
        'YEAR_': 'YEAR',
        'd_AGENCY': 'AGENCY',
        'd_UNIT_ID': 'UNIT_ID',
        'd_CAUSE': 'CAUSE',
        'd_OBJECTIVE': 'OBJECTIVE',
        'd_C_METHOD': 'C_METHOD'
    }
)

rxburn25 = rxburn25.rename(
    columns={
        'YEAR_': 'YEAR',
        'd_AGENCY': 'AGENCY',
        'd_UNIT_ID': 'UNIT_ID',
        'd_TREATMENT_TYPE': 'TREATMENT_TYPE',
        'd_PRE_CON_CLASS': 'PRE_CON_CLASS',
        'd_POST_CON_CLASS': 'POST_CON_CLASS',
        'd_RX_CONSUM': 'RX_CONSUM'
    }
)

In [36]:
#Report fire null values
print(fire25.isna().sum())

YEAR             77
AGENCY           48
UNIT_ID          62
FIRE_NAME      6655
INC_NUM         955
ALARM_DATE     5384
CONT_DATE     12618
GIS_ACRES         0
CAUSE             0
C_METHOD          0
OBJECTIVE       271
COMMENTS      20372
dtype: int64

In [37]:
#Report rxburn null values
print(rxburn25.isna().sum())

YEAR                 21
AGENCY                2
UNIT_ID              48
TREATMENT_ID        472
TREATMENT_TYPE     2115
START_DATE         1773
END_DATE           1973
GIS_ACRES             2
PRE_CON_CLASS     11472
POST_CON_CLASS    11472
RX_CONSUM         10899
dtype: int64

In [38]:
# Filter for data only after the year 2000
fire25_2000 = fire25.loc[fire25['YEAR'] >= 2000]
rxburn25_2000 = rxburn25.loc[rxburn25['YEAR'] >= 2000]

In [39]:
# Report info on filtered fire data
print(fire25_2000.info())
# Report info on filtered rxburn data
print(rxburn25_2000.info())

<class 'pandas.DataFrame'>
RangeIndex: 8892 entries, 0 to 8891
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR        8892 non-null   Int64
 1   AGENCY      8892 non-null   str
 2   UNIT_ID     8878 non-null   str
 3   FIRE_NAME   8841 non-null   str
 4   INC_NUM     8544 non-null   str
 5   ALARM_DATE  8850 non-null   datetime64[us]
 6   CONT_DATE   8496 non-null   datetime64[us]
 7   GIS_ACRES   8892 non-null   float64
 8   CAUSE       8892 non-null   str
 9   C_METHOD    8892 non-null   str
 10  OBJECTIVE   8717 non-null   str
 11  COMMENTS    2025 non-null   str
dtypes: Int64(1), datetime64[us](2), float64(1), str(8)
memory usage: 842.4 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 10105 entries, 0 to 10104
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   YEAR            10105 non-null  Int64
 1   AGENCY          10103 non-null  str
 2   UNIT_ID         10074 non-null  str
 3   TREATMENT_ID    9826 non-null   str
 4   TREATMENT_TYPE  9600 non-null   str
 5   START_DATE      8991 non-null   datetime64[us]
 6   END_DATE        9651 non-null   datetime64[us]
 7   GIS_ACRES       10103 non-null  float64
 8   PRE_CON_CLASS   441 non-null    str
 9   POST_CON_CLASS  441 non-null    str
 10  RX_CONSUM       731 non-null    str
dtypes: Int64(1), datetime64[us](2), float64(1), str(7)
memory usage: 878.4 KB
None

In [42]:
# Save filtered and cleaned data to processed folder
fire25_2000.to_csv(processed_fldr / 'fire25_2000.csv', index=False)
rxburn25_2000.to_csv(processed_fldr / 'rxburn25_2000.csv', index=False)