In [2]:
from pathlib import Path
import pandas as pd

In [3]:
#Create raw folder path
root_fldr = Path.cwd().parent
raw_fldr = root_fldr / "data" / "raw"

#Create raw csv file variables
fire25_csv = raw_fldr / "fire25_1.csv"
rxburn25_csv = raw_fldr / "rxburn25_1.csv"

#Import csv as data frames
fire25 = pd.read_csv(fire25_csv)
rxburn = pd.read_csv(rxburn25_csv)

In [4]:
#Report csv dimensions
print(fire25.shape)
print(rxburn.shape)

(23334, 20)
(11975, 16)

In [ ]:
#Report head of fire25
fire25.head()

,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,IRWINID,ALARM_DATE,CONT_DATE,C_METHOD,CAUSE,OBJECTIVE,GIS_ACRES,COMPLEX_ID,COMPLEX_NAME,COMMENTS,FIRE_NUM,Shape_Length,Shape_Area,GlobalID
0,2025.0,CA,USF,LPF,GIFFORD,00002181,{08A6358F-8301-4093-9988-E265C8F6F0A9},8/1/2025 0:00:00,10/14/2025 0:00:00,3,14,1.0,131613.531250,NaN,NaN,NaN,NaN,257388.320379,5.326211e+08,{E87207FF-BD3D-4836-8A89-AD218A20B17E}
1,2025.0,CA,USF,LPF,MADRE,00001817,{1AB682F7-CC0F-4DCE-87A4-FA4A9B67AB05},7/2/2025 0:00:00,7/26/2025 0:00:00,7,14,1.0,80779.101562,NaN,NaN,NaN,NaN,191846.167384,3.269014e+08,{C59C71E2-F79F-440B-8C84-48058988F3CF}
2,2025.0,CA,USF,SNF,GARNET,00001684,{68B988A1-C190-4F0C-9BEA-A658D389D167},8/24/2025 0:00:00,10/23/2025 0:00:00,3,1,1.0,60019.234375,NaN,NaN,NaN,NaN,234717.355087,2.428892e+08,{DDD0B278-7655-4F20-829D-FEEEF1DC935F}
3,2025.0,CA,CDF,FKU,SALT,00018739,{7F4A1474-6439-44F3-8F0D-083DCFD33639},9/2/2025 0:00:00,9/17/2025 0:00:00,7,1,1.0,25553.546875,NaN,NaN,Park incident clipped out per BEU,NaN,90080.360959,1.034115e+08,{6817A72C-90CF-4CD4-8F26-2B9622F1F140}
4,2025.0,CA,CDF,LDF,PALISADES,00000738,{A7EA5D21-F882-44B8-BF64-44AB11059DC1},1/7/2025 0:00:00,1/31/2025 0:00:00,7,14,1.0,23448.882812,NaN,NaN,NaN,NaN,116028.197349,9.489426e+07,{73730F90-5D60-4850-98C2-2431C4284CD7}

In [8]:
#Report head of rxburn
rxburn.head()

,YEAR_,STATE,AGENCY,UNIT_ID,TREATMENT_ID,TREATMENT_NAME,TREATMENT_TYPE,START_DATE,END_DATE,TREATED_AC,GIS_ACRES,RX_CONSUM,PRE_CON_CLASS,POST_CON_CLASS,Shape_Length,Shape_Area
0,2025.0,CA,BLM,CND,38441,BIL312D Stornetta Rx_FY25,3.0,10/1/2024 0:00:00,2/1/2025 0:00:00,15.0,14.621698,3.0,NaN,NaN,1104.323979,59171.913798
1,2025.0,CA,BLM,NOD,45361,BIL312D_FY25_Butte Pile RX,3.0,10/1/2024 0:00:00,2/1/2025 0:00:00,50.0,49.999985,4.0,NaN,NaN,1799.301659,202342.766575
2,2025.0,CA,BLM,NOD,38421,BIL312D_FY25_North Horse Pile RX,3.0,2/10/2025 0:00:00,2/12/2025 0:00:00,229.0,228.603134,4.0,NaN,NaN,5386.383188,925124.048407
3,2025.0,CA,BLM,NOD,40041,BIL312D_AGFO_WUI_Machine_Pile_Burn,3.0,10/1/2024 0:00:00,2/13/2025 0:00:00,116.0,116.124580,4.0,NaN,NaN,3960.591710,469939.500485
4,2025.0,CA,BLM,CND,41684,Black Forest Rx_FY25,3.0,10/1/2024 0:00:00,3/25/2025 0:00:00,25.0,25.118351,4.0,NaN,NaN,3452.593270,101650.358387